/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.29
 * Generated at: 2013-06-19 16:43:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hello_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");

  final String u_name = (String)session.getAttribute("username"),
               u_name_arg = u_name==null ? null : "\"" + u_name + "\"";

      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>WebApps Home</title>\n");
      out.write("        <link rel='stylesheet' type='text/css' href='styles/main.css'>\n");
      out.write("        <link rel='stylesheet' type='text/css' href='styles/home.css'>\n");
      out.write("    </head>\n");
      out.write("    \n");
      out.write("    <body>\n");
      out.write("        <div class='navbar'>\n");
      out.write("            <div id=\"u_info\">\n");
      out.write("                User: ");
      out.print( u_name==null ? "Guest" : u_name );
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <a id='login' \n");
      out.write("                onclick=\"document.location.href='/login.jsp';\"");
      out.print( u_name==null ? "" : "style=\"display:none;\"" );
      out.write("> \n");
      out.write("                Login\n");
      out.write("            </a>\n");
      out.write("            <a id='logout' onclick=\"document.location.href='/logout';\"");
      out.print( u_name==null ? "style=\"display:none;\"" : "" );
      out.write(">\n");
      out.write("                Logout\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <div class='game-accordion'>\n");
      out.write("            <section id='joinclosed'>\n");
      out.write("                <a onclick='toggleJoinForm();'><h2>Join Game</h2></a>\n");
      out.write("                    <form id='join-form' method='get' action='/wstest1.jsp'>\n");
      out.write("                        <p><input id='join-game' type='text' value='' placeholder='Room Number'></p> \n");
      out.write("                        <p><input id='submit-btn' type='button' onClick='reqJoin();' value='Join'></p>\n");
      out.write("                        <input type='hidden' name='real-data' value=''>\n");
      out.write("                    </form>\n");
      out.write("            </section>\n");
      out.write("            <section id='create'>\n");
      out.write("                <a onclick='reqCreation();'><h2>Create Game</h2></a>\n");
      out.write("            </section>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div id=\"test\"></div>\n");
      out.write("        <script>\n");
      out.write("          var joinForm = document.getElementById(\"join-form\");\n");
      out.write("\n");
      out.write("          var toggleJoinForm = showJoinForm;\n");
      out.write("            function showJoinForm(){\n");
      out.write("                document.getElementById(\"joinclosed\").id = 'joinopen';\n");
      out.write("                document.getElementById('join-game').focus();\n");
      out.write("                toggleJoinForm = closeJoinForm;\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            function closeJoinForm(){\n");
      out.write("                document.getElementById(\"joinopen\").id = 'joinclosed';\n");
      out.write("                toggleJoinForm = showJoinForm;\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            function reqCreation() {\n");
      out.write("                joinForm.elements[\"real-data\"].value=\"-1\";\n");
      out.write("                joinForm.submit();\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function reqJoin() {\n");
      out.write("                var joinField = document.getElementById('join-game');\n");
      out.write("                joinForm.elements[\"real-data\"].value\n");
      out.write("                    =joinField.value;\n");
      out.write("                joinField.value=\"\";\n");
      out.write("                joinForm.submit();\n");
      out.write("            }\n");
      out.write("       </script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
